### ISSUE TITLE
Palermo Website

### ISSUE THREAD

**Issue by cbacon93** [cbacon93/palermo#4]
Webseite fertigstellen

Startseite
Spielregeln
Kontakt
Über Uns
Impressum

Übergang zum Spiel

**Comment by wumix** [comment]
kann man denn schon eine demo sehen?

**Comment by cbacon93** [comment]
Noch nicht, ich denke zwei bis drei Wochen brauchen wir noch

**Comment by cbacon93** [comment]
@wumix schau mal hier: https://palermo.marcelhaupt.net/
